# -*- coding: utf-8 -*-
# Ghidra post-script: export a compact annotated assembly listing to rom.lst.
#
# Output strategy:
#   - Instructions:    full line (addr + bytes + mnemonic + operands + comments)
#   - Data regions:    collapse contiguous runs into a single summary line
#                      `<start>..<end>  DATA  (N bytes)  ; first-bytes or string`
#   - Labels:          always emitted (navigation anchors)
#   - Comments:        always emitted
#
# Rationale: Classic Mac ROMs embed fonts, icons, string tables, pattern
# resources, and checksum-protected data blocks. Disassembling them produces
# noise that dwarfs the actual code. Collapsing data runs keeps every
# symbolic anchor but strips embedded resources to one line per block.
#
# Invocation: -postScript export_listing.py <output_path>
# @category Mac.ROM
# @runtime Jython

import sys
import os
import io
from ghidra.program.model.listing import (
    Instruction, Data, CodeUnitFormat, CodeUnitFormatOptions
)

# A-line trap name lookup (inline for Jython compatibility)
try:
    import imp
    _script_dir = os.path.dirname(os.path.abspath(sourceFile.getAbsolutePath()))
    _traps_mod  = imp.load_source("mac_traps", os.path.join(_script_dir, "mac_traps.py"))
    _trap_mnemonic = _traps_mod.trap_mnemonic
except Exception:
    # Fallback: minimal inline table if mac_traps.py import fails
    _TRAPS = {
        0xA000:"_Open",0xA001:"_Close",0xA002:"_Read",0xA003:"_Write",
        0xA004:"_Control",0xA005:"_Status",0xA00F:"_MountVol",
        0xA019:"_InitZone",0xA01E:"_NewPtr",0xA022:"_NewHandle",
        0xA029:"_HLock",0xA02A:"_HUnlock",0xA02D:"_SetApplLimit",
        0xA02E:"_BlockMove",0xA02F:"_PostEvent",0xA036:"_MoreMasters",
        0xA04E:"_AddDrive",0xA058:"_InsTime",0xA059:"_RmvTime",
        0xA05A:"_PrimeTime",0xA063:"_MaxApplZone",0xA064:"_MoveHHi",
        0xA072:"_DoVBLTask",0xA07C:"_ADBOp",0xA11E:"_NewPtr",
        0xA122:"_NewHandle",0xA247:"_SetOSTrapAddress",
        0xA346:"_GetOSTrapAddress",0xA43D:"_DrvrInstallRsrvMem",
        0xA647:"_SetToolTrapAddress",0xA71E:"_NewPtrSysClear",
        0xA746:"_GetToolTrapAddress",
        0xA815:"_SCSIDispatch",0xA86E:"_InitGraf",0xA8FE:"_InitFonts",
        0xA912:"_InitWindows",0xA930:"_InitMenus",0xA970:"_GetNextEvent",
        0xA97B:"_InitDialogs",0xA995:"_InitResources",
        0xA997:"_OpenResFile",0xA99C:"_CountResources",
        0xA9A0:"_GetResource",0xA9C9:"_SysError",0xA9CC:"_TEInit",
        0xA9F2:"_Launch",0xA9F4:"_ExitToShell",
    }
    def _trap_mnemonic(w):
        if 0xA000 <= w <= 0xAFFF:
            return _TRAPS.get(w, "$%04X" % w)
        return None

args = getScriptArgs()
if len(args) < 1:
    print("export_listing.py: expected <output_path> argument")
    sys.exit(1)

output_path = args[0]
listing = currentProgram.getListing()
memory  = currentProgram.getMemory()
fm      = currentProgram.getFunctionManager()
st      = currentProgram.getSymbolTable()

# Binary-mode write with explicit UTF-8 encoding. rom_patches.cpp contains
# the occasional non-ASCII character (em-dashes, smart quotes) that gets
# imported verbatim into EOL comments; Jython default encoding is ASCII.
_raw_out = open(output_path, "wb")

class _Utf8Writer(object):
    def __init__(self, fp):
        self.fp = fp
    def write(self, s):
        if isinstance(s, unicode):
            self.fp.write(s.encode("utf-8"))
        else:
            # Bytes string: try as-is, fall back to latin-1 -> utf-8
            try:
                self.fp.write(s)
            except Exception:
                self.fp.write(s.decode("latin-1").encode("utf-8"))
    def close(self):
        self.fp.close()

out = _Utf8Writer(_raw_out)

prog = currentProgram
out.write("; ======================================================\n")
out.write(";  %s\n" % prog.getName())
out.write(";  Base: %s\n" % prog.getImageBase())
out.write(";  Language: %s\n" % prog.getLanguageID())
out.write(";  Generated by docs/roms/dissam/tools/export_listing.py\n")
out.write(";  Data regions are collapsed; see .rom file for raw bytes.\n")
out.write("; ======================================================\n\n")


def fmt_bytes(code_unit, max_bytes=8):
    try:
        b = code_unit.getBytes()
        n = min(len(b), max_bytes)
        s = " ".join("%02x" % (x & 0xFF) for x in b[:n])
        if len(b) > max_bytes:
            s += " .."
        return s
    except Exception:
        return ""


def fmt_ascii_preview(start_addr, length, max_chars=40):
    """Return a short ASCII preview of a data region, or '' if not printable."""
    try:
        n = min(length, max_chars)
        chars = []
        printable = 0
        for i in range(n):
            b = getByte(start_addr.add(i)) & 0xFF
            if 0x20 <= b < 0x7f:
                chars.append(chr(b))
                printable += 1
            elif b == 0:
                chars.append('.')
            else:
                chars.append('.')
        if printable >= max(4, n // 2):
            s = "".join(chars)
            if length > max_chars:
                s += ".."
            return s
    except Exception:
        pass
    return ""


# Formatter that resolves references to symbol names in operands.
cu_fmt = CodeUnitFormat(CodeUnitFormatOptions())

# Iterate only over initialized memory (skip RAM_LOMEM which is uninit stub)
init_set = memory.getLoadedAndInitializedAddressSet()
code_units = listing.getCodeUnits(init_set, True)
current_fn = None

# Data-run accumulator state
data_start = None
data_end   = None   # inclusive
data_bytes = 0


def flush_data_run():
    """Emit one summary line for the accumulated data run, then reset."""
    global data_start, data_end, data_bytes
    if data_start is None:
        return
    preview = fmt_ascii_preview(data_start, data_bytes)
    line = "%s..%s  DATA  (%d bytes)" % (data_start, data_end, data_bytes)
    if preview:
        line += "   ; \"%s\"" % preview
    out.write(line + "\n")
    data_start = None
    data_end = None
    data_bytes = 0


for cu in code_units:
    addr = cu.getAddress()
    is_instr = isinstance(cu, Instruction)

    # Labels and comments force-flush any pending data run so they stay aligned.
    symbols = st.getSymbols(addr)
    has_label = False
    for sym in symbols:
        # Skip auto-generated DAT_/LAB_/SUB_ labels inside data runs to keep
        # the collapse tight. Keep them at instruction boundaries and for
        # imported/user-defined symbols.
        name = sym.getName()
        if name.startswith("DAT_") or name.startswith("LAB_") or name.startswith("SUB_"):
            if not is_instr:
                continue
        has_label = True
        break

    fn = fm.getFunctionContaining(addr)
    is_fn_entry = fn is not None and fn.getEntryPoint().equals(addr)
    plate = listing.getComment(3, addr)
    pre   = listing.getComment(0, addr)
    eol   = listing.getComment(1, addr)
    post  = listing.getComment(2, addr)

    # Decide whether to break the data run
    break_run = is_instr or has_label or is_fn_entry or plate or pre or eol or post

    if break_run:
        flush_data_run()

        # Emit function header
        if is_fn_entry and fn != current_fn:
            current_fn = fn
            out.write("\n")
            if plate:
                for l in plate.split("\n"):
                    out.write("; %s\n" % l)
                plate = None  # already consumed
            out.write("%s:\n" % fn.getName())

        # Emit standalone label (non-function)
        if has_label and not is_fn_entry:
            for sym in symbols:
                name = sym.getName()
                if name.startswith("DAT_") or name.startswith("LAB_") or name.startswith("SUB_"):
                    if not is_instr:
                        continue
                out.write("%s:\n" % name)
                break

        # Plate (if not consumed above)
        if plate:
            for l in plate.split("\n"):
                out.write("; %s\n" % l)

        # Pre-comment
        if pre:
            for l in pre.split("\n"):
                out.write("    ; %s\n" % l)

    if is_instr:
        mnemonic = cu_fmt.getRepresentationString(cu)
        line = "%s  %s" % (addr, mnemonic)
        if eol:
            line += "   ; %s" % eol
        out.write(line + "\n")
        if post:
            for l in post.split("\n"):
                out.write("    ; %s\n" % l)
    else:
        # Check for A-line traps: 2-byte Data units with opcode $A000-$AFFF.
        # Ghidra doesn't decode these as instructions (they're Mac-specific
        # A-line exceptions), but they're critical for understanding ROM flow.
        length = cu.getLength()
        if length == 2:
            try:
                w = (getByte(addr) & 0xFF) << 8 | (getByte(addr.add(1)) & 0xFF)
                if 0xA000 <= w <= 0xAFFF:
                    flush_data_run()
                    line = "%s  %s" % (addr, _trap_mnemonic(w))
                    if eol:
                        line += "   ; %s" % eol
                    out.write(line + "\n")
                    continue
            except Exception:
                pass

        # Data: either has a meaningful label/comment (already emitted above
        # during break_run), or we start/extend a data run to collapse.
        if eol or post:
            # One-off comment on a data unit: emit it with the data repr
            line = "%s  %s" % (addr, cu_fmt.getRepresentationString(cu))
            if eol:
                line += "   ; %s" % eol
            out.write(line + "\n")
            if post:
                for l in post.split("\n"):
                    out.write("    ; %s\n" % l)
        else:
            if data_start is None:
                data_start = addr
            data_end = addr.add(length - 1)
            data_bytes += length

# Final flush
flush_data_run()
out.close()
print("export_listing.py: wrote %s" % output_path)
