/*
 * command_bridge.cpp - Host-side command dispatcher for controlling Mac OS
 *
 * Read commands (app name, window list, memory) peek Mac memory directly
 * from the 60Hz IRQ — safe because no Toolbox calls are needed.
 *
 * Action commands (launch, quit) work through a BridgeINIT that is embedded
 * in the emulator binary and injected at boot. The INIT installs a jGNEFilter
 * that polls for command files on the ExtFS "Host" volume. Communication is
 * entirely file-based — the host writes _bridge_cmd, the INIT reads it,
 * executes the command, and writes _bridge_result.
 *
 * Legacy path: for backward compatibility, the old mailbox + Execute68kTrap
 * approach is kept behind the same code paths but the bridge INIT is preferred
 * when --bridge is enabled.
 */

#include "command_bridge.h"
#include "../common/include/sysdeps.h"
#include "../common/include/cpu_emulation.h"
#include "../common/include/m68k_registers.h"
#include "../common/include/platform.h"
#include "boot_progress.h"
#include "../config/emulator_config.h"
#include "../common/include/emul_op.h"
#include <cstdio>
#include <cstring>
#include <unistd.h>
#include <cstring>
#include <chrono>
#include <thread>
#include <atomic>
#include <algorithm>

// Embedded BridgeINIT flat binary (generated by xxd from Retro68 build)
#include "bridge_init_code.h"

// Global instance (used for in-process mode, kept for compatibility)
CommandBridge g_command_bridge;

extern uint8 *ScratchMem;  // Platform scratch memory pointer (set during CPU init)

// ScratchMem layout — addresses computed at runtime from ScratchMem pointer.
// ScratchMem points to the MIDDLE of a 64KB block (original convention).
// We use offsets from the base (ScratchMem - 0x8000) to place our data
// in the upper half where it won't conflict with ROM patches.
static uint32_t SCRATCH_BASE;     // Mac address of ScratchMem base
static uint32_t FILTER_CODE;      // jGNEFilter code (66 bytes)
static uint32_t MAILBOX;          // command mailbox

// Mailbox field offsets (relative to MAILBOX, set in init_addresses)
static uint32_t MB_CMD_FLAG;      // uint8: 1 = command pending
static uint32_t MB_RESULT_FLAG;   // uint8: 1 = result ready
static uint32_t MB_CMD_TYPE;      // int16: 1=LAUNCH, 2=QUIT
static uint32_t MB_LAUNCH_READY;  // uint8: 1 = LPB prepared, 2 = launch error
static uint32_t MB_LAUNCH_LPB;    // uint32: LaunchParamBlockRec pointer
static uint32_t MB_RESULT_ERR;    // int16: Mac OS error code
static uint32_t MB_CMD_ARG;       // Pascal string (256 bytes)
static uint32_t MB_RESULT_DATA;   // result text (256 bytes)

static bool g_addresses_initialized = false;

static void init_addresses() {
    if (g_addresses_initialized) return;
    if (!ScratchMem || !RAMBaseHost) return;

    // ScratchMem points to the middle of a 64KB block.
    // Compute Mac address of the base.
    SCRATCH_BASE = Host2MacAddr(ScratchMem);
    // ScratchMem itself is at base + 0x8000 (middle), but we use offsets
    // from the Mac address of ScratchMem directly since that's what the
    // log shows and what ReadMacInt/WriteMacInt expect.
    // Place our structures in the upper range to avoid ROM patch conflicts.
    FILTER_CODE     = SCRATCH_BASE + 0x400;
    MAILBOX         = SCRATCH_BASE + 0x800;
    MB_CMD_FLAG     = MAILBOX + 0;
    MB_RESULT_FLAG  = MAILBOX + 1;
    MB_CMD_TYPE     = MAILBOX + 2;
    MB_RESULT_ERR   = MAILBOX + 4;
    MB_CMD_ARG      = MAILBOX + 6;
    MB_LAUNCH_READY = MAILBOX + 0x80;
    MB_LAUNCH_LPB   = MAILBOX + 0x84;
    MB_RESULT_DATA  = MAILBOX + 0x106;

    g_addresses_initialized = true;
    fprintf(stderr, "[CommandBridge] Addresses: SCRATCH_BASE=0x%08X FILTER=0x%08X MAILBOX=0x%08X\n",
            SCRATCH_BASE, FILTER_CODE, MAILBOX);
}

// Mailbox command types
static const int16_t MB_CMD_LAUNCH = 1;
static const int16_t MB_CMD_QUIT   = 2;

// jGNEFilter low memory global
static const uint32_t LM_JGNEFILTER = 0x29A;

// Whether the jGNEFilter has been installed
static std::atomic<bool> g_filter_installed{false};

// Bridge INIT state
static bool g_bridge_init_injected = false;
static uint32_t g_bridge_filter_addr = 0;  // INIT's filter address (read from 0x29A after injection)

// ============================================================================
// Bridge INIT injection (replaces hand-coded jGNEFilter when --bridge is set)
// ============================================================================

/*
 * Inject the BridgeINIT into Mac memory and call its entry point.
 *
 * The INIT is a Retro68 flat binary with relocation data. When called,
 * RETRO68_RELOCATE() fixes up absolute references, then _start() installs
 * a jGNEFilter that polls for command files on the ExtFS "Host" volume.
 *
 * The INIT is placed at SCRATCH_BASE + 0x1000 (upper half of ScratchMem,
 * above the mailbox at +0x800 and legacy filter at +0x400).
 */
static void inject_bridge_init() {
    if (g_bridge_init_injected) return;
    if (!RAMBaseHost || RAMSize == 0) return;
    init_addresses();

    uint32_t init_addr = SCRATCH_BASE + 0x1000;

    // Check if the INIT fits in ScratchMem (64KB total, we start at +0x1000)
    if (BridgeINIT_flt_len > 0xF000) {
        fprintf(stderr, "[Bridge] INIT too large (%u bytes, max %u)\n",
                BridgeINIT_flt_len, 0xF000);
        return;
    }

    // Copy INIT code to Mac memory
    uint8_t *dest = Mac2HostAddr(init_addr);
    memcpy(dest, BridgeINIT_flt, BridgeINIT_flt_len);

    // Save current jGNEFilter before INIT overwrites it
    uint32_t old_filter = ReadMacInt32(LM_JGNEFILTER);

    // Call the INIT entry point — RETRO68_RELOCATE + filter installation
    M68kRegisters regs;
    memset(&regs, 0, sizeof(regs));
    Execute68k(init_addr, &regs);

    // Read the filter address the INIT installed
    g_bridge_filter_addr = ReadMacInt32(LM_JGNEFILTER);

    g_bridge_init_injected = true;
    fprintf(stderr, "[Bridge] INIT injected at 0x%08X (%u bytes), filter=0x%08X (old=0x%08X)\n",
            init_addr, BridgeINIT_flt_len, g_bridge_filter_addr, old_filter);
}

// ============================================================================
// Legacy jGNEFilter installation (fallback when --bridge is not set)
// ============================================================================

/*
 * Install a jGNEFilter in ScratchMem.
 *
 * The filter runs in real Finder app context (called from GetNextEvent) on
 * every event loop iteration. Two responsibilities:
 *   1. If MB_CMD_FLAG is set, trigger an EmulOp to run the C++ command
 *      dispatcher (handles read commands + launch-prep).
 *   2. If MB_LAUNCH_READY is set, execute _Launch INLINE with the LPB
 *      pointer from MB_LAUNCH_LPB. This runs _Launch as a normal 68k
 *      instruction in the filter's own context — no Execute68kTrap
 *      reentry, no Process Manager deadlock.
 *
 * After _Launch returns (with launchContinue it always does), the filter
 * saves D0 (error code) to MB_RESULT_ERR so the host can detect failures.
 * D0=0 means success; the Process Manager will switch to the new app on
 * the next WaitNextEvent cycle.
 *
 * 68k code at FILTER_CODE (60 bytes):
 *
 *   0x00: 207C xxxx xxxx  MOVEA.L  #MAILBOX, A0
 *   0x06: 4A10            TST.B    (A0)           ; MB_CMD_FLAG?
 *   0x08: 6702            BEQ.S    +2 → 0x0C
 *   0x0A: 71xx            EmulOp   CMD_DISPATCH
 *   0x0C: 207C xxxx xxxx  MOVEA.L  #MAILBOX, A0   ; reload (EmulOp may clobber)
 *   0x12: 4A28 0080       TST.B    0x80(A0)       ; MB_LAUNCH_READY?
 *   0x16: 6714            BEQ.S    +20 → 0x2C
 *   0x18: 4228 0080       CLR.B    0x80(A0)       ; clear ready flag
 *   0x1C: 2068 0084       MOVEA.L  0x84(A0), A0   ; A0 = LPB ptr (MB_LAUNCH_LPB)
 *   0x20: A9F2            _Launch                 ; INLINE launch — returns with launchContinue
 *   --- _Launch returned (D0.W = 0 on success, <0 on error) ---
 *   0x22: 207C xxxx xxxx  MOVEA.L  #MAILBOX, A0   ; reload A0
 *   0x28: 3140 0004       MOVE.W   D0, 0x04(A0)   ; MB_RESULT_ERR = D0
 *   --- chain to old filter ---
 *   0x2C: 207A 000A       MOVEA.L  oldFilter(PC), A0
 *   0x30: 4A88            TST.L    A0
 *   0x32: 6702            BEQ.S    +2 → 0x36
 *   0x34: 4ED0            JMP      (A0)
 *   0x36: 4E75            RTS
 *   0x38: 0000 0000       oldFilter: DC.L 0
 */
static void install_jgne_filter() {
    if (g_filter_installed.load(std::memory_order_acquire)) return;
    if (!RAMBaseHost || RAMSize == 0) return;
    init_addresses();

    uint16_t emulop = platform_make_emulop(M68K_EMUL_OP_CMD_DISPATCH);

    uint32_t p = FILTER_CODE;
    WriteMacInt16(p + 0x00, 0x207C);      // MOVEA.L #imm, A0
    WriteMacInt32(p + 0x02, MAILBOX);      //   #MAILBOX
    WriteMacInt16(p + 0x06, 0x4A10);      // TST.B (A0)              — MB_CMD_FLAG
    WriteMacInt16(p + 0x08, 0x6702);      // BEQ.S +2
    WriteMacInt16(p + 0x0A, emulop);      // EmulOp CMD_DISPATCH
    WriteMacInt16(p + 0x0C, 0x207C);      // MOVEA.L #imm, A0        — reload
    WriteMacInt32(p + 0x0E, MAILBOX);      //   #MAILBOX
    WriteMacInt16(p + 0x12, 0x4A28);      // TST.B d(A0)
    WriteMacInt16(p + 0x14, 0x0080);      //   d=0x80 (MB_LAUNCH_READY)
    WriteMacInt16(p + 0x16, 0x6714);      // BEQ.S +20 → chain at 0x2C
    WriteMacInt16(p + 0x18, 0x4228);      // CLR.B d(A0)
    WriteMacInt16(p + 0x1A, 0x0080);      //   d=0x80
    WriteMacInt16(p + 0x1C, 0x2068);      // MOVEA.L d(A0), A0
    WriteMacInt16(p + 0x1E, 0x0084);      //   d=0x84 (MB_LAUNCH_LPB)
    WriteMacInt16(p + 0x20, 0xA9F2);      // _Launch                 — returns with launchContinue
    // --- _Launch returned: D0 = 0 (success) or error code ---
    WriteMacInt16(p + 0x22, 0x207C);      // MOVEA.L #imm, A0        — reload
    WriteMacInt32(p + 0x24, MAILBOX);      //   #MAILBOX
    WriteMacInt16(p + 0x28, 0x3140);      // MOVE.W D0, d(A0)
    WriteMacInt16(p + 0x2A, 0x0004);      //   d=0x04 (MB_RESULT_ERR)
    // --- chain to old filter ---
    WriteMacInt16(p + 0x2C, 0x207A);      // MOVEA.L d(PC), A0
    WriteMacInt16(p + 0x2E, 0x000A);      //   d → oldFilter at 0x38
    WriteMacInt16(p + 0x30, 0x4A88);      // TST.L A0
    WriteMacInt16(p + 0x32, 0x6702);      // BEQ.S +2
    WriteMacInt16(p + 0x34, 0x4ED0);      // JMP (A0)
    WriteMacInt16(p + 0x36, 0x4E75);      // RTS
    // Save old filter and install ours
    uint32_t old_filter = ReadMacInt32(LM_JGNEFILTER);
    WriteMacInt32(p + 0x38, old_filter);  // oldFilter storage
    WriteMacInt32(LM_JGNEFILTER, FILTER_CODE);

    // Clear mailbox
    WriteMacInt8(MB_CMD_FLAG, 0);
    WriteMacInt8(MB_RESULT_FLAG, 0);
    WriteMacInt8(MB_LAUNCH_READY, 0);
    WriteMacInt32(MB_LAUNCH_LPB, 0);

    g_filter_installed.store(true, std::memory_order_release);
    fprintf(stderr, "[CommandBridge] jGNEFilter installed at 0x%08X (old=0x%08X, emulop=0x%04X)\n",
            FILTER_CODE, old_filter, emulop);
}

// ============================================================================
// EmulOp handler — called from jGNEFilter in application context
// ============================================================================

/*
 * Handle M68K_EMUL_OP_CMD_DISPATCH.
 * Called from the jGNEFilter during GetNextEvent/WaitNextEvent,
 * so we're in full application context — Toolbox calls are safe.
 */
void command_bridge_dispatch(M68kRegisters* /*r*/) {
    uint8_t cmd_flag = ReadMacInt8(MB_CMD_FLAG);
    if (!cmd_flag) return;

    int16_t cmd_type = static_cast<int16_t>(ReadMacInt16(MB_CMD_TYPE));
    fprintf(stderr, "[CommandBridge] dispatch: cmd_type=%d\n", cmd_type);

    // Clear command flag immediately to prevent re-entry
    WriteMacInt8(MB_CMD_FLAG, 0);

    switch (cmd_type) {

    case MB_CMD_LAUNCH: {
        // App path is a Pascal string at MB_CMD_ARG in the form "Volume:Name".
        //
        // Strategy:
        //   1. Iterate mounted volumes via _HGetVInfo to resolve "Volume" -> vRefNum
        //   2. Build an FSSpec for the leaf at the volume root
        //   3. Build an extended LaunchParamBlockRec with launchContinue
        //   4. Hand off to the filter (MB_LAUNCH_READY / MB_LAUNCH_LPB) which
        //      executes _Launch inline in real Finder app context — calling
        //      Execute68kTrap(_Launch) here would deadlock the Process Manager.

        uint8_t namelen = ReadMacInt8(MB_CMD_ARG);
        char name[256];
        for (int i = 0; i < namelen && i < 255; i++)
            name[i] = static_cast<char>(ReadMacInt8(MB_CMD_ARG + 1 + i));
        name[namelen] = '\0';
        fprintf(stderr, "[CommandBridge] LAUNCH path='%s' len=%d\n", name, namelen);

        // --- Step 1: Resolve "Volume:..." path to (vRefNum, leaf) ---
        // Walks mounted volumes with _HGetVInfo (HParamBlockRec):
        //   +16 ioResult, +18 ioNamePtr, +22 ioVRefNum, +28 ioVolIndex
        uint32_t pb_addr       = SCRATCH_BASE + 0xC00;
        uint32_t fsspec_addr   = SCRATCH_BASE + 0xD00;
        uint32_t vol_name_addr = SCRATCH_BASE + 0xE80;

        int colon_pos = -1;
        for (int i = 0; i < namelen; i++) {
            if (name[i] == ':') { colon_pos = i; break; }
        }

        int16_t  vRefNum    = 0;
        uint32_t parID      = 0;  // 0 = resolve colon-separated path from volume root
        int      leaf_start = 0;

        if (colon_pos >= 0) {
            char volname[64];
            int vnlen = colon_pos > 63 ? 63 : colon_pos;
            for (int i = 0; i < vnlen; i++) volname[i] = name[i];
            volname[vnlen] = '\0';

            bool found = false;
            for (int16_t idx = 1; idx < 16 && !found; idx++) {
                for (int i = 0; i < 108; i++) WriteMacInt8(pb_addr + i, 0);
                WriteMacInt8(vol_name_addr, 0);
                WriteMacInt32(pb_addr + 18, vol_name_addr);
                WriteMacInt16(pb_addr + 22, 0);
                WriteMacInt16(pb_addr + 28, idx);

                M68kRegisters vi_regs;
                memset(&vi_regs, 0, sizeof(vi_regs));
                vi_regs.a[0] = pb_addr;
                Execute68kTrap(0xA207, &vi_regs);  // _HGetVInfo

                if (ReadMacInt16(pb_addr + 16) != 0) break;

                uint8_t rvnlen = ReadMacInt8(vol_name_addr);
                {
                    char vn[64] = {};
                    for (int i = 0; i < rvnlen && i < 63; i++)
                        vn[i] = ReadMacInt8(vol_name_addr + 1 + i);
                    fprintf(stderr, "[CommandBridge] Vol[%d] = '%s' (vRefNum=%d)\n",
                            idx, vn, (int16_t)ReadMacInt16(pb_addr + 22));
                }
                if (rvnlen == (uint8_t)vnlen) {
                    bool match = true;
                    for (int i = 0; i < vnlen; i++) {
                        if (ReadMacInt8(vol_name_addr + 1 + i) != (uint8_t)volname[i]) {
                            match = false;
                            break;
                        }
                    }
                    if (match) {
                        vRefNum = static_cast<int16_t>(ReadMacInt16(pb_addr + 22));
                        found = true;
                    }
                }
            }

            if (!found) {
                fprintf(stderr, "[CommandBridge] Volume '%s' not found (nsvErr)\n", volname);
                WriteMacInt16(MB_RESULT_ERR, -35);  // nsvErr
                WriteMacInt8(MB_RESULT_FLAG, 1);
                break;
            }
            fprintf(stderr, "[CommandBridge] Volume '%s' -> vRefNum=%d\n", volname, vRefNum);
            leaf_start = colon_pos + 1;
        }

        // Resolve colon-separated path directory-by-directory using _PBHGetCatInfo.
        // Split "MPW-PR:MPW:MPW Shell" into components and walk each one.
        uint32_t cur_dirID = 2;  // start at root (fsRtDirID)
        int path_pos = leaf_start;
        char component[64];

        while (path_pos < namelen) {
            // Extract next path component (up to colon or end)
            int comp_len = 0;
            while (path_pos + comp_len < namelen && name[path_pos + comp_len] != ':' && comp_len < 63)
                comp_len++;

            for (int i = 0; i < comp_len; i++) component[i] = name[path_pos + i];
            component[comp_len] = '\0';

            bool is_last = (path_pos + comp_len >= namelen || name[path_pos + comp_len] != ':');

            if (is_last) {
                // Last component = the filename. Build FSSpec directly.
                WriteMacInt16(fsspec_addr + 0, vRefNum);
                WriteMacInt32(fsspec_addr + 2, cur_dirID);
                WriteMacInt8(fsspec_addr + 6, comp_len);
                for (int i = 0; i < comp_len; i++)
                    WriteMacInt8(fsspec_addr + 7 + i, static_cast<uint8_t>(component[i]));
                break;
            }

            // Intermediate component = directory. Resolve via _PBHGetCatInfo.
            uint32_t path_str_addr = SCRATCH_BASE + 0xE80;
            WriteMacInt8(path_str_addr, comp_len);
            for (int i = 0; i < comp_len; i++)
                WriteMacInt8(path_str_addr + 1 + i, static_cast<uint8_t>(component[i]));

            for (int i = 0; i < 108; i++) WriteMacInt8(pb_addr + i, 0);
            WriteMacInt32(pb_addr + 18, path_str_addr);  // ioNamePtr
            WriteMacInt16(pb_addr + 22, vRefNum);         // ioVRefNum
            WriteMacInt16(pb_addr + 28, 0);               // ioFDirIndex = 0
            WriteMacInt32(pb_addr + 48, cur_dirID);       // ioDirID

            M68kRegisters ci_regs;
            memset(&ci_regs, 0, sizeof(ci_regs));
            ci_regs.a[0] = pb_addr;
            ci_regs.d[0] = 9;                 // selector for PBGetCatInfo
            Execute68kTrap(0xA260, &ci_regs);  // _HFSDispatch(PBGetCatInfo)

            int16_t ci_err = static_cast<int16_t>(ReadMacInt16(pb_addr + 16));
            if (ci_err != 0) {
                fprintf(stderr, "[CommandBridge] Dir '%s' not found (err=%d, dirID=%u)\n",
                        component, ci_err, cur_dirID);
                WriteMacInt16(MB_RESULT_ERR, ci_err);
                WriteMacInt8(MB_RESULT_FLAG, 1);
                break;  // break out of while loop
            }

            // For directories: ioFlAttrib bit 4 is set, ioDrDirID at +48
            uint8_t attrib = ReadMacInt8(pb_addr + 30);
            int16_t ci_result = static_cast<int16_t>(ReadMacInt16(pb_addr + 16));
            fprintf(stderr, "[CommandBridge] CatInfo: result=%d attrib=0x%02X dirID_48=%u parID_100=%u\n",
                    ci_result, attrib, ReadMacInt32(pb_addr + 48), ReadMacInt32(pb_addr + 100));
            if (attrib & 0x10) {
                // It's a directory — ioDrDirID at +48 has the dir's own ID
                cur_dirID = ReadMacInt32(pb_addr + 48);
            } else {
                // It's a file in an intermediate position — error
                fprintf(stderr, "[CommandBridge] '%s' is a file, not a directory\n", component);
                WriteMacInt16(MB_RESULT_ERR, -120);  // dirNFErr
                WriteMacInt8(MB_RESULT_FLAG, 1);
                break;
            }
            fprintf(stderr, "[CommandBridge] Dir '%s' -> dirID=%u (attrib=0x%02X)\n",
                    component, cur_dirID, attrib);

            path_pos += comp_len + 1;  // skip component + colon
        }

        // Check if path resolution failed (result already written)
        if (ReadMacInt8(MB_RESULT_FLAG)) break;

        fprintf(stderr, "[CommandBridge] FSSpec: vRefNum=%d parID=%u name='%s'\n",
                vRefNum, cur_dirID, component);

        // --- Step 2: Build extended LaunchParamBlockRec ---
        // Layout from Inside Macintosh: Processes, Ch.2:
        //   +0  reserved1              (LongInt)       = 0
        //   +4  reserved2              (Word)          = 0
        //   +6  launchBlockID          (Word)          = 'LC' = 0x4C43
        //   +8  launchEPBLength        (LongInt)       = extendedBlockLen = sizeof-12 = 34
        //   +12 launchFileFlags        (Word)          = 0
        //   +14 launchControlFlags     (LongInt)       = launchContinue | launchNoFileFlags
        //   +18 launchAppSpec          (FSSpecPtr)     = FSSpec ptr
        //   +22 launchProcessSN        (8 bytes)       = 0 (return slot)
        //   +30 launchPreferredSize    (LongInt)       = 0
        //   +34 launchMinimumSize      (LongInt)       = 0
        //   +38 launchAvailableSize    (LongInt)       = 0
        //   +42 launchAppParameters    (AppParamsPtr)  = 0
        // Total size: 46 bytes
        const int LPB_SIZE = 48;   // round up
        uint32_t lpb_addr = SCRATCH_BASE + 0xE00;
        for (int i = 0; i < LPB_SIZE; i++)
            WriteMacInt8(lpb_addr + i, 0);
        WriteMacInt16(lpb_addr + 6, 0x4C43);              // launchBlockID = 'LC'
        WriteMacInt32(lpb_addr + 8, 32);                   // launchEPBLength (44 - 12)
        WriteMacInt16(lpb_addr + 12, 0);                   // launchFileFlags (Integer)
        WriteMacInt16(lpb_addr + 14, 0x4000 | 0x0800);    // launchControlFlags (LaunchFlags = uint16!)
        WriteMacInt32(lpb_addr + 16, fsspec_addr);         // launchAppSpec (FSSpecPtr at +16)
        // +20..+27 launchProcessSN (8 bytes, zeroed)
        // +28..+39 sizes (zeroed → use app SIZE resource defaults)
        WriteMacInt32(lpb_addr + 40, 0);                   // launchAppParameters = none

        // --- Step 3: Call _Launch via Execute68kTrap ---
        //
        // With launchContinue, _Launch queues the app and returns immediately.
        // No deadlock — same mechanism as _HGetVInfo above.
        {
            M68kRegisters launch_regs;
            memset(&launch_regs, 0, sizeof(launch_regs));
            launch_regs.a[0] = lpb_addr;
            Execute68kTrap(0xA9F2, &launch_regs);  // _Launch

            int16_t launch_err = static_cast<int16_t>(launch_regs.d[0]);
            fprintf(stderr, "[CommandBridge] _Launch returned err=%d (LPB=0x%08X, FSSpec=0x%08X, vRefNum=%d)\n",
                    launch_err, lpb_addr, fsspec_addr, vRefNum);

            WriteMacInt16(MB_RESULT_ERR, launch_err);
            WriteMacInt8(MB_RESULT_FLAG, 1);
        }
        break;
    }

    case MB_CMD_QUIT: {
        fprintf(stderr, "[CommandBridge] INIT quitting current app\n");

        WriteMacInt16(MB_RESULT_ERR, 0);
        WriteMacInt8(MB_RESULT_FLAG, 1);

        M68kRegisters quit_regs;
        memset(&quit_regs, 0, sizeof(quit_regs));
        Execute68kTrap(0xA9F4, &quit_regs);  // _ExitToShell — doesn't return
        break;
    }

    default:
        fprintf(stderr, "[CommandBridge] Unknown mailbox command: %d\n", cmd_type);
        WriteMacInt16(MB_RESULT_ERR, -1);
        WriteMacInt8(MB_RESULT_FLAG, 1);
        break;
    }
}

// ============================================================================
// In-process queue (legacy, kept for compatibility)
// ============================================================================

uint32_t CommandBridge::submit(Command cmd) {
    std::lock_guard<std::mutex> lock(mutex_);
    cmd.id = next_id_.fetch_add(1);
    pending_.push(std::move(cmd));
    return cmd.id;
}

bool CommandBridge::wait_result(uint32_t id, CommandResult& out, int timeout_ms) {
    std::unique_lock<std::mutex> lock(mutex_);
    auto deadline = std::chrono::steady_clock::now() + std::chrono::milliseconds(timeout_ms);

    while (true) {
        auto it = results_.find(id);
        if (it != results_.end()) {
            out = std::move(it->second);
            results_.erase(it);
            return true;
        }
        if (cv_.wait_until(lock, deadline) == std::cv_status::timeout) {
            return false;
        }
    }
}

void CommandBridge::drain(M68kRegisters* r) {
    Command cmd;
    {
        std::lock_guard<std::mutex> lock(mutex_);
        if (pending_.empty()) return;
        cmd = std::move(pending_.front());
        pending_.pop();
    }

    CommandResult result;
    result.id = cmd.id;
    result.done = true;

    execute_one_public(cmd, r, result);

    {
        std::lock_guard<std::mutex> lock(mutex_);
        results_[cmd.id] = std::move(result);
    }
    cv_.notify_all();
}

// ============================================================================
// Read commands — peek Mac memory, no Toolbox calls needed
// ============================================================================

CommandResult CommandBridge::execute_read(CmdType type, uint32_t addr, uint32_t len) {
    CommandResult result;
    result.done = true;

    if (!RAMBaseHost || RAMSize == 0) {
        result.err = -1;
        result.data = "";
        return result;
    }

    switch (type) {

    case CmdType::GET_APP_NAME: {
        uint8_t namelen = ReadMacInt8(0x0910);
        if (namelen > 31) namelen = 31;
        char name[32];
        for (int i = 0; i < namelen; i++)
            name[i] = static_cast<char>(ReadMacInt8(0x0911 + i));
        name[namelen] = '\0';
        result.data = name;
        break;
    }

    case CmdType::GET_TICKS: {
        uint32_t ticks = ReadMacInt32(0x016A);
        result.data = std::to_string(ticks);
        break;
    }

    case CmdType::GET_WINDOW_LIST: {
        std::string json = "[";
        uint32_t wp = ReadMacInt32(0x09D6);
        bool first = true;
        int limit = 50;

        while (wp && wp < 0x02000000 && limit-- > 0) {
            if (!first) json += ",";
            first = false;

            std::string title;
            uint32_t title_handle = ReadMacInt32(wp + 134);
            if (title_handle) {
                uint32_t title_ptr = ReadMacInt32(title_handle);
                if (title_ptr && title_ptr < 0x02000000) {
                    uint8_t tlen = ReadMacInt8(title_ptr);
                    if (tlen > 0) {
                        for (int i = 0; i < tlen; i++) {
                            char c = static_cast<char>(ReadMacInt8(title_ptr + 1 + i));
                            if (c == '"' || c == '\\') json += "\\";
                            title += c;
                        }
                    }
                }
            }

            int16_t top = static_cast<int16_t>(ReadMacInt16(wp + 16));
            int16_t left = static_cast<int16_t>(ReadMacInt16(wp + 18));
            int16_t bottom = static_cast<int16_t>(ReadMacInt16(wp + 20));
            int16_t right = static_cast<int16_t>(ReadMacInt16(wp + 22));
            bool visible = ReadMacInt8(wp + 110) != 0;

            json += "{\"title\":\"" + title + "\""
                 +  ",\"rect\":[" + std::to_string(left) + ","
                 +  std::to_string(top) + ","
                 +  std::to_string(right) + ","
                 +  std::to_string(bottom) + "]"
                 +  ",\"visible\":" + (visible ? "true" : "false") + "}";

            wp = ReadMacInt32(wp + 144);
        }
        json += "]";
        result.data = json;
        break;
    }

    case CmdType::READ_MEMORY: {
        uint32_t read_len = std::min(len, (uint32_t)1024);
        std::string hex;
        hex.reserve(read_len * 2);
        for (uint32_t i = 0; i < read_len; i++) {
            char buf[4];
            snprintf(buf, sizeof(buf), "%02x", ReadMacInt8(addr + i));
            hex += buf;
        }
        result.data = hex;
        break;
    }

    default:
        result.err = -1;
        result.data = "not a read command";
        break;
    }

    return result;
}

// ============================================================================
// Command execution — read commands direct, action commands via mailbox
// ============================================================================

void CommandBridge::execute_one_public(const Command& cmd, M68kRegisters* /*r*/, CommandResult& result) {
    switch (cmd.type) {

    case CmdType::GET_APP_NAME:
    case CmdType::GET_TICKS:
    case CmdType::GET_WINDOW_LIST:
    case CmdType::READ_MEMORY:
        result = execute_read(cmd.type, cmd.addr, cmd.len);
        result.id = cmd.id;
        break;

    case CmdType::LAUNCH_APP: {
        const std::string& path = cmd.arg;
        auto plen = static_cast<uint8_t>(std::min<size_t>(path.size(), 255));

        // No pre-validation here — _GetFileInfo can't parse "Volume:File" paths
        // and we're in IRQ context where full Toolbox calls aren't safe.
        // The dispatcher (Side B, app context) does volume-aware lookup and
        // reports errors via MB_RESULT_ERR.
        //
        // Write path to mailbox and set command flag.
        // The jGNEFilter will pick it up on the next event loop iteration
        // and execute _Launch in application context.
        WriteMacInt8(MB_RESULT_FLAG, 0);
        WriteMacInt16(MB_CMD_TYPE, MB_CMD_LAUNCH);
        WriteMacInt8(MB_CMD_ARG, plen);
        for (int i = 0; i < plen; i++)
            WriteMacInt8(MB_CMD_ARG + 1 + i, static_cast<uint8_t>(path[i]));
        WriteMacInt8(MB_CMD_FLAG, 1);  // signal to jGNEFilter

        result.err = 0;
        result.data = "launched";
        fprintf(stderr, "[CommandBridge] Launch queued for INIT: %s\n", path.c_str());
        break;
    }

    case CmdType::QUIT_APP: {
        WriteMacInt8(MB_RESULT_FLAG, 0);
        WriteMacInt16(MB_CMD_TYPE, MB_CMD_QUIT);
        WriteMacInt8(MB_CMD_FLAG, 1);

        result.err = 0;
        result.data = "quit";
        fprintf(stderr, "[CommandBridge] Quit queued for INIT\n");
        break;
    }

    }  // switch
}

// ============================================================================
// Launch result polling — called from API handler thread
// ============================================================================

bool command_bridge_poll_launch_result(int16_t& err, int timeout_ms) {
    if (!RAMBaseHost || RAMSize == 0 || !g_addresses_initialized) {
        err = -1;
        return false;
    }

    auto deadline = std::chrono::steady_clock::now() + std::chrono::milliseconds(timeout_ms);
    while (std::chrono::steady_clock::now() < deadline) {
        uint8_t result_flag = ReadMacInt8(MB_RESULT_FLAG);
        uint8_t launch_ready = ReadMacInt8(MB_LAUNCH_READY);

        if (result_flag) {
            // Dispatch completed (volume lookup, FSSpec build, etc.)
            err = static_cast<int16_t>(ReadMacInt16(MB_RESULT_ERR));
            fprintf(stderr, "[CommandBridge] poll: result_flag=%d launch_ready=%d err=%d\n",
                    result_flag, launch_ready, err);
            if (err != 0) return true;  // dispatch-level error (e.g. nsvErr)

            if (launch_ready == 0) {
                // Filter already consumed the launch and ran _Launch.
                // With launchContinue, _Launch returns and the filter writes
                // D0 (error code) to MB_RESULT_ERR. Give it a moment, then
                // re-read in case the filter wrote a non-zero error.
                std::this_thread::sleep_for(std::chrono::milliseconds(200));
                err = static_cast<int16_t>(ReadMacInt16(MB_RESULT_ERR));
                fprintf(stderr, "[CommandBridge] poll: after 200ms, err=%d\n", err);
                return true;
            }

            // launch_ready == 1 — filter hasn't picked it up yet, keep polling
        }

        std::this_thread::sleep_for(std::chrono::milliseconds(50));
    }
    return false;  // timeout
}

// ============================================================================
// INIT bridge — guest INIT communicates via EmulOp (no mailbox addresses)
// ============================================================================

// INIT filter address — set when INIT calls EmulOp 0xFE, installed later by IRQ
static uint32_t g_init_filter_addr = 0;
static bool g_init_filter_installed = false;

// Pending action command for the INIT to pick up
static std::mutex g_init_mutex;
static std::condition_variable g_init_cv;
static bool g_init_cmd_pending = false;
static std::string g_init_cmd_path;
static int16_t g_init_cmd_type = 0;

// Result from the INIT
static bool g_init_result_ready = false;
static int16_t g_init_result_err = 0;

/*
 * Called from M68K_EMUL_OP_INIT_BRIDGE handler (app context, from guest INIT).
 *
 * D0=0 (CHECK): Guest polls for a pending command.
 *   If pending: copy path to buffer at A0, set D0=cmd_type, D1=path_length
 *   If nothing: set D0=0
 *
 * D0=0x80 (RESULT): Guest reports command completion.
 *   D1 = Mac OS error code (0 = noErr)
 */
void command_bridge_init_bridge(M68kRegisters* r) {
    uint32_t sub_op = r->d[0];

    if (sub_op == 0xFF) {
        fprintf(stderr, "[InitBridge] INIT loaded! Bridge ready.\n");
        return;
    }
    if (sub_op == 0xFD) {
        static int heartbeat = 0;
        if (++heartbeat <= 3)
            fprintf(stderr, "[InitBridge] Filter heartbeat #%d — filter is running!\n", heartbeat);
        return;
    }

    if (sub_op == 0xFE) {
        // INIT reports its filter address — we'll install it after boot stabilizes
        g_init_filter_addr = r->d[1];
        fprintf(stderr, "[InitBridge] INIT filter at 0x%08X — will install after boot\n",
                g_init_filter_addr);
        return;
    }

    if (sub_op == 0) {
        // CHECK: is there a pending command?
        static int check_count = 0;
        if (++check_count <= 3)
            fprintf(stderr, "[InitBridge] CHECK #%d (filter is alive)\n", check_count);

        std::lock_guard<std::mutex> lock(g_init_mutex);
        if (!g_init_cmd_pending) {
            r->d[0] = 0;  // nothing pending
            return;
        }

        // Copy path to guest buffer at A0
        uint32_t buf_addr = r->a[0];
        auto path = g_init_cmd_path;
        auto plen = static_cast<uint8_t>(std::min<size_t>(path.size(), 255));
        WriteMacInt8(buf_addr, plen);  // Pascal string: length byte
        for (int i = 0; i < plen; i++)
            WriteMacInt8(buf_addr + 1 + i, static_cast<uint8_t>(path[i]));

        r->d[0] = g_init_cmd_type;   // 1=LAUNCH, 2=QUIT
        r->d[1] = plen;

        g_init_cmd_pending = false;
        fprintf(stderr, "[InitBridge] CHECK: delivering cmd=%d path='%s'\n",
                g_init_cmd_type, path.c_str());

    } else if (sub_op == 0x80) {
        // RESULT: INIT completed the command
        int16_t err = static_cast<int16_t>(r->d[1]);
        fprintf(stderr, "[InitBridge] RESULT: err=%d\n", err);

        std::lock_guard<std::mutex> lock(g_init_mutex);
        g_init_result_err = err;
        g_init_result_ready = true;
        g_init_cv.notify_all();
    }
}

/*
 * Submit an action command for the INIT to pick up.
 * Called from the API handler after submit() drains through IRQ.
 */
void command_bridge_submit_to_init(int16_t cmd_type, const std::string& path) {
    std::lock_guard<std::mutex> lock(g_init_mutex);
    g_init_cmd_type = cmd_type;
    g_init_cmd_path = path;
    g_init_cmd_pending = true;
    g_init_result_ready = false;
    g_init_result_err = 0;
}

/*
 * Wait for the INIT to report a result.
 * Called from the API handler thread.
 */
bool command_bridge_wait_init_result(int16_t& err, int timeout_ms) {
    std::unique_lock<std::mutex> lock(g_init_mutex);
    auto deadline = std::chrono::steady_clock::now() + std::chrono::milliseconds(timeout_ms);

    while (!g_init_result_ready) {
        if (g_init_cv.wait_until(lock, deadline) == std::cv_status::timeout) {
            return false;
        }
    }

    err = g_init_result_err;
    g_init_result_ready = false;
    return true;
}

// ============================================================================
// Entry point from emul_op.cpp IRQ handler
// ============================================================================

void command_bridge_drain_from_irq(M68kRegisters* r) {
    // Check bridge config — read from the global emulator config
    static bool bridge_checked = false;
    static bool bridge_enabled = false;
    if (!bridge_checked) {
        auto& cfg = config::EmulatorConfig::instance();
        bridge_enabled = cfg.bridge_enabled;
        bridge_checked = true;
    }

    if (!g_filter_installed.load(std::memory_order_acquire)) {
        if (bridge_enabled) {
            // Inject the compiled BridgeINIT — installs a file-driven jGNEFilter
            inject_bridge_init();
        }
        // Also install legacy jGNEFilter (for read commands via CMD_DISPATCH)
        install_jgne_filter();
    }

    // Deferred reinstall: after Finder starts, other extensions may have
    // overwritten 0x29A. Reinstall the bridge INIT's filter.
    if (bridge_enabled && g_bridge_filter_addr != 0 && !g_init_filter_installed
        && boot_progress_phase_reached("Finder")) {
        uint32_t current_filter = ReadMacInt32(LM_JGNEFILTER);
        if (current_filter != g_bridge_filter_addr) {
            WriteMacInt32(LM_JGNEFILTER, g_bridge_filter_addr);
            fprintf(stderr, "[Bridge] Reinstalled filter at 0x29A: 0x%08X (was 0x%08X)\n",
                    g_bridge_filter_addr, current_filter);
        }
        g_init_filter_installed = true;
    }

    // Drain in-process command queue (legacy path)
    g_command_bridge.drain(r);
}
