/*
 * command_bridge.cpp - Host-side command dispatcher for controlling Mac OS
 *
 * Read commands (app name, window list, memory) peek Mac memory directly
 * from the 60Hz IRQ — safe because no Toolbox calls are needed.
 *
 * Action commands (launch, quit) are handled by the BridgeINIT, a compiled
 * Retro68 INIT embedded in the emulator binary. At boot, the INIT is
 * allocated via _NewPtrSys and called via Execute68k. It installs a
 * jGNEFilter that polls for command files on the ExtFS "Host" volume.
 *
 * Communication is entirely file-based:
 *   Host writes Host:_bridge_cmd  → INIT reads, executes, deletes
 *   INIT writes Host:_bridge_result → Host reads, returns to API caller
 *
 * No EmulOps. No hand-coded 68k. No mailbox in ScratchMem.
 */

#include "command_bridge.h"
#include "../common/include/sysdeps.h"
#include "../common/include/cpu_emulation.h"
#include "../common/include/m68k_registers.h"
#include "../common/include/platform.h"
#include "boot_progress.h"
#include "bridge_fs.h"
#include "../config/emulator_config.h"
#include <cstdio>
#include <cstring>
#include <atomic>

// Embedded BridgeINIT flat binary (generated by xxd from Retro68 build)
#include "bridge_init_code.h"

extern uint8 *ScratchMem;

// jGNEFilter low memory global
static const uint32_t LM_JGNEFILTER = 0x29A;

// Bridge INIT state
static bool g_bridge_init_injected = false;
static uint32_t g_bridge_filter_addr = 0;
static bool g_bridge_filter_reinstalled = false;

// ============================================================================
// Bridge INIT injection
// ============================================================================

/*
 * Inject the BridgeINIT into Mac memory and call its entry point.
 *
 * Allocates memory in the Mac System heap via _NewPtrSys (safe, won't
 * conflict with ScratchMem or application heap). The INIT's _start()
 * calls RETRO68_RELOCATE() to fix up addresses, then installs a
 * jGNEFilter that polls for command files.
 *
 * Works on both m68k (native) and PPC (via Mac's built-in 68k emulator).
 */
static void inject_bridge_init() {
    if (g_bridge_init_injected) return;
    if (RAMSize == 0) return;

    // Initialize BridgeFS in-memory store (used by ExtFS intercept)
    if (!g_bridge_fs) {
        g_bridge_fs = new BridgeFS();
        auto& cfg = config::EmulatorConfig::instance();
        if (!cfg.bridge_dir.empty())
            g_bridge_fs->set_bridge_dir(cfg.bridge_dir);
    }

    // Allocate in Mac System heap
    M68kRegisters alloc_regs;
    memset(&alloc_regs, 0, sizeof(alloc_regs));
    alloc_regs.d[0] = BridgeINIT_flt_len;
    Execute68kTrap(0xA51E, &alloc_regs);  // _NewPtrSys
    uint32_t init_addr = alloc_regs.a[0];
    if (init_addr == 0) {
        fprintf(stderr, "[Bridge] _NewPtrSys(%u) failed\n", BridgeINIT_flt_len);
        return;
    }

    // Copy INIT code to allocated block
    memcpy(Mac2HostAddr(init_addr), BridgeINIT_flt, BridgeINIT_flt_len);

    uint32_t old_filter = ReadMacInt32(LM_JGNEFILTER);

    // Call entry point — RETRO68_RELOCATE + filter installation
    M68kRegisters regs;
    memset(&regs, 0, sizeof(regs));
    Execute68k(init_addr, &regs);

    // Read the filter address the INIT installed
    g_bridge_filter_addr = ReadMacInt32(LM_JGNEFILTER);
    g_bridge_init_injected = true;

    fprintf(stderr, "[Bridge] INIT injected at 0x%08X (%u bytes), filter=0x%08X (old=0x%08X)\n",
            init_addr, BridgeINIT_flt_len, g_bridge_filter_addr, old_filter);
}

// ============================================================================
// Read commands — peek Mac memory, no Toolbox calls needed
// ============================================================================

CommandResult command_bridge_read(CmdType type, uint32_t addr, uint32_t len) {
    CommandResult result;
    result.done = true;

    if (RAMSize == 0) {
        result.err = -1;
        return result;
    }

    switch (type) {

    case CmdType::GET_APP_NAME: {
        uint8_t namelen = ReadMacInt8(0x0910);
        if (namelen > 31) namelen = 31;
        char name[32];
        for (int i = 0; i < namelen; i++)
            name[i] = static_cast<char>(ReadMacInt8(0x0911 + i));
        name[namelen] = '\0';
        result.data = name;
        break;
    }

    case CmdType::GET_TICKS: {
        result.data = std::to_string(ReadMacInt32(0x016A));
        break;
    }

    case CmdType::GET_WINDOW_LIST: {
        std::string json = "[";
        uint32_t wp = ReadMacInt32(0x09D6);
        bool first = true;
        int limit = 50;

        while (wp && wp < RAMSize && limit-- > 0) {
            if (!first) json += ",";
            first = false;

            std::string title;
            uint32_t title_handle = ReadMacInt32(wp + 134);
            if (title_handle) {
                uint32_t title_ptr = ReadMacInt32(title_handle);
                if (title_ptr && title_ptr < RAMSize) {
                    uint8_t tlen = ReadMacInt8(title_ptr);
                    for (int i = 0; i < tlen; i++) {
                        char c = static_cast<char>(ReadMacInt8(title_ptr + 1 + i));
                        if (c == '"' || c == '\\') json += "\\";
                        title += c;
                    }
                }
            }

            int16_t top = static_cast<int16_t>(ReadMacInt16(wp + 16));
            int16_t left = static_cast<int16_t>(ReadMacInt16(wp + 18));
            int16_t bottom = static_cast<int16_t>(ReadMacInt16(wp + 20));
            int16_t right = static_cast<int16_t>(ReadMacInt16(wp + 22));
            bool visible = ReadMacInt8(wp + 110) != 0;

            json += "{\"title\":\"" + title + "\""
                 +  ",\"rect\":[" + std::to_string(left) + ","
                 +  std::to_string(top) + ","
                 +  std::to_string(right) + ","
                 +  std::to_string(bottom) + "]"
                 +  ",\"visible\":" + (visible ? "true" : "false") + "}";

            wp = ReadMacInt32(wp + 144);
        }
        json += "]";
        result.data = json;
        break;
    }

    case CmdType::READ_MEMORY: {
        uint32_t read_len = std::min(len, (uint32_t)1024);
        std::string hex;
        hex.reserve(read_len * 2);
        for (uint32_t i = 0; i < read_len; i++) {
            char buf[4];
            snprintf(buf, sizeof(buf), "%02x", ReadMacInt8(addr + i));
            hex += buf;
        }
        result.data = hex;
        break;
    }

    default:
        result.err = -1;
        result.data = "not a read command";
        break;
    }

    return result;
}

// ============================================================================
// IRQ entry point — called from 60Hz timer (m68k and PPC)
// ============================================================================

static void drain_from_irq_impl(M68kRegisters* r) {
    (void)r;

    static bool bridge_checked = false;
    static bool bridge_enabled = false;
    if (!bridge_checked) {
        bridge_enabled = config::EmulatorConfig::instance().bridge_enabled;
        bridge_checked = true;
    }

    if (!bridge_enabled) return;

    // Inject the BridgeINIT once at boot
    if (!g_bridge_init_injected) {
        inject_bridge_init();
    }

    // After Finder starts, other extensions may have overwritten 0x29A.
    // Reinstall the bridge INIT's filter.
    // Gate on CurApName containing "Finder" — works on both m68k and PPC
    // (boot_progress_phase_reached doesn't detect Finder on PPC)
    bool finder_running = false;
    if (RAMSize > 0) {
        uint8_t namelen = ReadMacInt8(0x0910);
        if (namelen == 6) {
            finder_running = (ReadMacInt8(0x0911) == 'F' && ReadMacInt8(0x0912) == 'i');
        }
    }
    // Advance boot_phase on PPC where window heuristic doesn't work.
    // Only set FINDER phase (not DESKTOP — that triggers auto-launch timing).
    if (finder_running && !boot_progress_phase_reached("Finder")
        && ReadMacInt32(0x09D6) == 0 /* WindowList empty = PPC */) {
        static bool ppc_phase_set = false;
        if (!ppc_phase_set) {
            boot_progress_phase_reached("Finder");  // no-op, just checking
            // Set Finder phase directly via the low-level API
            extern void boot_progress_set_phase_finder(void);
            boot_progress_set_phase_finder();
            ppc_phase_set = true;
        }
    }

    if (g_bridge_filter_addr != 0 && !g_bridge_filter_reinstalled && finder_running) {
        uint32_t current = ReadMacInt32(LM_JGNEFILTER);
        if (current != g_bridge_filter_addr) {
            WriteMacInt32(LM_JGNEFILTER, g_bridge_filter_addr);
            fprintf(stderr, "[Bridge] Reinstalled filter at 0x29A: 0x%08X (was 0x%08X)\n",
                    g_bridge_filter_addr, current);
        }
        g_bridge_filter_reinstalled = true;
    }
}

void command_bridge_drain_from_irq(M68kRegisters* r) { drain_from_irq_impl(r); }
void command_bridge_drain_from_irq_ppc(M68kRegisters* r) { drain_from_irq_impl(r); }
