#!/bin/bash
#
# make-source-tarball.sh — produce a self-contained source tarball that can
# be built offline by Debian / RPM packaging tooling.
#
# What goes in:
#   - Tracked files from HEAD (git archive)
#   - All git submodules (subprojects/{unicorn,libdatachannel,nlohmann_json,lwip})
#   - Vendored cargo crates for net-bridge/ (cargo vendor → net-bridge/vendor/cargo)
#   - net-bridge/.cargo/config.toml so `cargo build --offline` resolves vendored
#
# What stays out:
#   - build/, test_roms/, private/, test-results/, node_modules/, .git/
#   - Pre-built openssl-legacy artifacts (rebuilt on demand by net-bridge tools)
#
# Output: dist/mac-phoenix_<version>.tar.xz   (Debian "3.0 (native)" naming)
#
# Usage:
#   tools/make-source-tarball.sh [version]
#
# version defaults to the project() VERSION in CMakeLists.txt.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

VERSION="${1:-}"
if [[ -z "$VERSION" ]]; then
    # Match the VERSION token in the project() call: project(name VERSION X.Y.Z LANGUAGES ...)
    VERSION="$(awk '/^project\(mac-phoenix/ {
        for (i = 1; i <= NF; i++) if ($i == "VERSION") { print $(i+1); exit }
    }' CMakeLists.txt)"
fi
if [[ -z "$VERSION" ]]; then
    echo "ERROR: could not determine version (pass as arg)" >&2
    exit 1
fi

PKG="mac-phoenix"
DIST="$ROOT/dist"
STAGE="$DIST/${PKG}-${VERSION}"
TARBALL="$DIST/${PKG}_${VERSION}.tar.xz"

command -v git >/dev/null   || { echo "git not installed" >&2; exit 1; }
command -v cargo >/dev/null || { echo "cargo not installed (apt install cargo)" >&2; exit 1; }
command -v xz >/dev/null    || { echo "xz not installed (apt install xz-utils)" >&2; exit 1; }

echo "[tarball] version: $VERSION"
echo "[tarball] staging: $STAGE"

rm -rf "$STAGE" "$TARBALL"
mkdir -p "$STAGE"

# 1. Tracked + modified + untracked-not-gitignored files from main repo.
# (`git archive` only ever sees committed trees, so it misses new files added
# but never committed — `git ls-files` enumerates the working tree directly.)
echo "[tarball] exporting main repo..."
git ls-files --cached --modified --others --exclude-standard -z \
    | tar --null --files-from=- -cf - \
    | tar -x -C "$STAGE"

# 2. Each registered submodule (read from .gitmodules — ignores stale legacy/ dirs)
echo "[tarball] exporting submodules..."
git config --file .gitmodules --get-regexp '^submodule\..*\.path$' \
    | awk '{print $2}' | while read -r sub; do
    [[ -d "$sub/.git" || -f "$sub/.git" ]] || { echo "[tarball]   skip $sub (uninitialized)"; continue; }
    echo "[tarball]   $sub"
    mkdir -p "$STAGE/$sub"
    (cd "$sub" && git archive --format=tar HEAD) | tar -x -C "$STAGE/$sub"
done

# 3. Vendor cargo crates for offline build
echo "[tarball] vendoring cargo crates..."
mkdir -p "$STAGE/net-bridge/.cargo"
(cd "$STAGE/net-bridge" && cargo vendor --locked vendor/cargo > /dev/null)
# Downgrade Cargo.lock to format v3 so older distro cargos can read it
# (Ubuntu 24.04 ships cargo 1.75 which only handles up to v3; modern host
# cargo emits v4). v3 is a strict subset of v4 for our crate set.
sed -i 's/^version = 4$/version = 3/' "$STAGE/net-bridge/Cargo.lock"
cat > "$STAGE/net-bridge/.cargo/config.toml" <<'EOF'
# Generated by tools/make-source-tarball.sh — points cargo at the bundled
# vendor/cargo/ tree so the Rust net-bridge can build with --offline.
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor/cargo"
EOF

# 4. Drop hefty/unwanted bits that snuck in via submodule archives or stray files.
# (Trim under subprojects/ only — cargo vendor's checksum manifests reference
# every file, including .github/, so trimming them breaks offline builds.)
echo "[tarball] trimming..."
find "$STAGE/subprojects" -type d \( -name '.github' -o -name '.ci' \) -prune -exec rm -rf {} +
rm -rf "$STAGE/net-bridge/vendor/openssl-build"   # rebuilt on demand
rm -rf "$STAGE/net-bridge/vendor/openssl-legacy"  # rebuilt on demand
rm -rf "$STAGE/test_roms" "$STAGE/private" "$STAGE/test-results"
rm -rf "$STAGE/node_modules" "$STAGE/build"
rm -rf "$STAGE/toolchain"                         # Retro68 — not needed for distro builds
rm -rf "$STAGE/legacy"                            # BasiliskII reference source, not compiled
# Submodule fat: examples / docs / tests not needed for the actual library build
rm -rf "$STAGE/subprojects/libdatachannel/examples"
rm -rf "$STAGE/subprojects/libdatachannel/pages"
rm -rf "$STAGE/subprojects/libdatachannel/test"
rm -rf "$STAGE/subprojects/nlohmann_json/docs"
rm -rf "$STAGE/subprojects/nlohmann_json/tests"
rm -rf "$STAGE/subprojects/nlohmann_json/tools"
rm -rf "$STAGE/subprojects/nlohmann_json/benchmarks"
rm -rf "$STAGE/subprojects/unicorn/qemu/tests"

# 5. Pack
echo "[tarball] packing → $TARBALL"
tar -C "$DIST" -cJf "$TARBALL" "${PKG}-${VERSION}"

# Show resulting size and top-level content for sanity
du -sh "$TARBALL"
tar -tJf "$TARBALL" | awk -F/ '{print $2}' | sort -u | head -30

echo "[tarball] done."
