#!/usr/bin/env python3
"""
png2icn.py — convert a PNG to classic Mac icon-family Rez data blocks.

Reads a 32×32 PNG (and optionally a 16×16 PNG) and emits:
  data 'ICN#' (id) { ... };   -- 32×32 1-bit + mask
  data 'ics#' (id) { ... };   -- 16×16 1-bit + mask

The result is a snippet you can `#include` from a .r file or
concatenate into one. Use a single id per app — Mac OS pairs the
ICN# and ics# (and BNDL / FREF) by matching id.

Usage:
    png2icn.py --in32 globe-32.png --in16 globe-16.png \\
               --id 128 --out icons.r

Bit packing: 32×32 image plane = 32 rows × 32 bits = 4 bytes/row =
128 bytes total. ICN# is image-then-mask (256 B). 16×16 ics# is
2 B/row × 16 = 32 B image + 32 B mask = 64 B.

Mask convention: opaque (alpha > 127) pixels are mask=1; image bit
is 1 where the pixel is dark (luminance < 128), 0 where light. This
lets the Finder's white background show through the rounded
"transparent" corners without requiring a separate mask source.

For now this only emits 1-bit families (ICN# + ics#). Color variants
(icl4, icl8, ics4, ics8) need a Mac-system palette quantizer, which
is a follow-up — modern Macs have rendered this fine for years.
"""
from __future__ import annotations
import argparse
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("png2icn.py: PIL/Pillow not available (apt install python3-pil)")


def to_planes(img: Image.Image, w: int, h: int) -> tuple[bytes, bytes]:
    """Return (image_plane, mask_plane). Both are big-endian bit-packed
    rows of `w` bits each, MSB first, padded to byte boundary."""
    if img.size != (w, h):
        img = img.resize((w, h), Image.LANCZOS)
    img = img.convert("RGBA")
    pixels = img.load()
    bytes_per_row = (w + 7) // 8
    image = bytearray(bytes_per_row * h)
    mask  = bytearray(bytes_per_row * h)
    for y in range(h):
        for x in range(w):
            r, g, b, a = pixels[x, y]
            byte = y * bytes_per_row + (x >> 3)
            bit  = 0x80 >> (x & 7)
            # Mask: opaque if alpha > threshold.
            if a > 127:
                mask[byte] |= bit
                # Image bit: dark if luminance < 128.
                lum = (299*r + 587*g + 114*b) // 1000
                if lum < 128:
                    image[byte] |= bit
            # Transparent pixels leave both planes 0 — Finder will
            # composite the desktop background through.
    return bytes(image), bytes(mask)


def hex_bytes(b: bytes, group_size: int = 16) -> str:
    """Format bytes as Rez `$"AABB CCDD ..."` literal, wrapped to
    `group_size` bytes per literal (Rez can take long lines but
    chunking keeps it diff-friendly)."""
    out = []
    for i in range(0, len(b), group_size):
        chunk = b[i:i+group_size]
        out.append('    $"' + chunk.hex().upper() + '"')
    return "\n".join(out)


def emit_resource(rtype: str, rid: int, image: bytes, mask: bytes) -> str:
    return (
        f"data '{rtype}' ({rid}) {{\n"
        f"{hex_bytes(image + mask)}\n"
        f"}};\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--in32", required=True, type=Path,
                    help="32×32 PNG source (resized if needed)")
    ap.add_argument("--in16", type=Path,
                    help="16×16 PNG source (defaults to a downscale of --in32)")
    ap.add_argument("--id", type=int, default=128,
                    help="resource id for both ICN# and ics# (default 128)")
    ap.add_argument("--out", required=True, type=Path,
                    help="output .r snippet")
    args = ap.parse_args()

    src32 = Image.open(args.in32)
    src16 = Image.open(args.in16) if args.in16 else src32
    img32, mask32 = to_planes(src32, 32, 32)
    img16, mask16 = to_planes(src16, 16, 16)

    out  = "/* Generated by tools/png2icn.py — do not edit by hand. */\n\n"
    out += emit_resource("ICN#", args.id, img32, mask32)
    out += "\n"
    out += emit_resource("ics#", args.id, img16, mask16)

    args.out.write_text(out)
    print(f"png2icn: wrote {args.out} (ICN#/ics# id={args.id})", file=sys.stderr)


if __name__ == "__main__":
    main()
